export enum ENUM_BACKEND_NOTIFICATION {
    CREATE_BOOKING = 'BACKEND.CREATE_BOOKING',
    CREATE_BOOKING_FOR_STUDENT = 'BACKEND.CREATE_BOOKING_FOR_STUDENT',
    CREATE_BOOKING_FOR_TEACHER = 'BACKEND.CREATE_BOOKING_FOR_TEACHER',
    CREATE_BOOKING_FOR_ADMIN = 'BACKEND.CREATE_BOOKING_FOR_ADMIN',
    UPDATE_STATUS_BOOKING = 'BACKEND.UPDATE_STATUS_BOOKING',
    TEACHER_LATE_TO_CLASS = 'BACKEND.TEACHER_LATE_TO_CLASS',
    TEACHER_LATE_TO_CLASS_FOR_STUDENT = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_STUDENT',
    TEACHER_LATE_TO_CLASS_FOR_TEACHER = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_TEACHER',
    TEACHER_LATE_TO_CLASS_FOR_ADMIN = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_ADMIN',
    TEACHER_HAVE_MONTHLY_MEMOS_TO_COMMENT = 'BACKEND.TEACHER_HAVE_MONTHLY_MEMOS_TO_COMMENT',
    TEACHER_HAVE_LATE_MONTHLY_MEMOS = 'BACKEND.TEACHER_HAVE_LATE_MONTHLY_MEMOS',
    TEACHER_HAS_UPGRADE_REQUEST_FOR_ADMIN = 'BACKEND.TEACHER_HAS_UPGRADE_REQUEST_FOR_ADMIN',
    TEACHER_HAVE_NEW_COURSE_MEMO = 'BACKEND.TEACHER_HAVE_NEW_COURSE_MEMO',
    TEACHER_HAVE_LATE_COURSE_MEMO = 'BACKEND.TEACHER_HAVE_LATE_COURSE_MEMO',
    TEACHER_HAVE_NEW_REGULAR_CALENDAR = 'BACKEND.TEACHER_HAVE_NEW_REGULAR_CALENDAR',
    STUDENT_ORDER_NEARLY_OUT_OF_CLASS = 'BACKEND.STUDENT_ORDER_NEARLY_OUT_OF_CLASS',
    NEW_SALE_OFF = 'BACKEND.NEW_SALE_OFF',
    COMPLETED_CLASS_WITHOUT_RATING = 'BACKEND.COMPLETED_CLASS_WITHOUT_RATING',
    SUBSTITUTE_BOOKING_FOR_STUDENT = 'BACKEND.SUBSTITUTE_BOOKING_FOR_STUDENT',
    SUBSTITUTE_BOOKING_FOR_ADMIN = 'BACKEND.SUBSTITUTE_BOOKING_FOR_ADMIN',
    ALERT_ORDERED_PACKAGE_WILL_EXPIRE = 'BACKEND.ALERT_ORDERED_PACKAGE_WILL_EXPIRE',
    ALERT_OVER_ABSENT_COURSE = 'BACKEND.ALERT_OVER_ABSENT_COURSE',
    ALERT_DO_NOT_HOMEWORK = 'BACKEND.ALERT_DO_NOT_HOMEWORK'
}

export enum ENUM_BACKEND_EVENT {
    HAPPY_BIRTHDAY_EVENT = 'BACKEND.HAPPY_BIRTHDAY_EVENT'
}

export const NotificationTemplateSubject = 'BACKEND.TEMPLATE';
export const NotificationBroadcastSubject = 'BACKED.ALL_USER';
export const PopUpEndBookingEvent = 'BACKEND.BOOKING_END_CLASS';
